version: '3.0'

networks:
  hw-10:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php:7.4.1-fpm
    container_name: hillel_hw10_test_php
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - hw-10

  webserver:
    image: nginx:alpine
    container_name: hillel_hw10_test_nginx
    restart: unless-stopped
    tty: true
    ports: 
      - "7777:80"
    volumes:
     - ./:/var/www
     - ./nginx/:/etc/nginx/conf.d/
    networks: 
      - hw-10